before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
  - deploy

assembleDebug:
  image: jangrewe/gitlab-ci-android
  stage: build
  only:
    - develop
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk

assembleRelease:
  image: jangrewe/gitlab-ci-android
  stage: build
  only:
    - main
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release-unsigned.apk

deploy_development:
  image: node:latest
  stage: deploy
  only:
    - develop
  script:
    - npm install -g firebase-tools
    - firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk
      --app "$FIREBASE_APP_ID_DEV"
      --release-notes "This is release notes from dev"
      --groups "group-dev"
      --token "$FIREBASE_CI_TOKEN"

deploy_production:
  image: node:latest
  stage: deploy
  only:
    - main
  script:
    - npm install -g firebase-tools
    - firebase appdistribution:distribute app/build/outputs/apk/release/app-release-unsigned.apk
      --app "$FIREBASE_APP_ID_PROD"
      --release-notes "This is release notes from prod"
      --groups "group-prod"
      --token "$FIREBASE_CI_TOKEN"