name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#   test:
#     name: Run Unit Tests
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'
#         cache: gradle
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Running unit tests
#       run: ./gradlew test --stacktrace
  
#   build:
#     name: Build app
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'
#         cache: gradle
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build

  apk:
    name: Generate and Distribute APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate apk debug
      run: ./gradlew assembleDebug --stacktrace
    - name: TREE DIRECTORY
      run: tree .
    - name: Upload APK to artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: my-app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Distribute APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: group-dev
        file: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
      
